server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: utilpoll
#  profiles:
#    active: dev
  datasource:
    username: remoteman
    password: 520Bu1314-
    url: jdbc:mysql://8.129.208.37:3306/learn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 5
    maxIdle: 5
    maxWait: 120000
    minEvictableIdleTimeMillis: 300000
    minIdle: 2
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: select 1 from dual
    whenExhaustedAction: 1
    dbcp:
      logAbandoned: false
      removeAbandoned: true
      removeAbandonedTimeout: 3000
      filterswitch: 0
jasypt:
  encryptor:
    password: sunshine


